<a href="https://colab.research.google.com/github/bella470/Python_Class_DST/blob/main/Fourth_class_python_JULY2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Find the missing value in the list below

list_missing = [1, 4, 3, 2, 5, 8,7]

sort

code to check difference between two item (5 + i)

sort guna list then for loop, if difference between 2 num

In [1]:
list_missing = [1, 4, 3, 2, 5, 8, 7, 10]

# Sort the list
list_missing.sort()

# Initialize an empty list to store missing numbers
missing_numbers = []

# Iterate through the sorted list and find missing numbers
for i in range(len(list_missing) - 1):
  current_num = list_missing[i]
  next_num = list_missing[i + 1]

# If the difference between consecutive numbers is more than 1,
# add the missing numbers to the list
  if next_num - current_num > 1:
      for missing in range(current_num + 1, next_num):
          missing_numbers.append(missing)

#return missing_numbers
print ('The missing number is:', missing_numbers)

The missing number is: [6, 9]


In [ ]:
def find_missing_numbers(list_missing):
   # Sort the list
   list_missing.sort()

   # Initialize an empty list to store missing numbers
   missing_numbers = []

   # Iterate through the sorted list and find missing numbers
   for i in range(len(list_missing) - 1):
      current_num = list_missing[i]
      next_num = list_missing[i + 1]

   # If the difference between consecutive numbers is more than 1,
   # add the missing numbers to the list
      if next_num - current_num > 1:
          for missing in range(current_num + 1, next_num):
              missing_numbers.append(missing)

   #return missing_numbers
   print ('The missing number is:', missing_numbers)

In [8]:
def missing_value(list_missing_value):

  list_missing_value = sorted (list_missing_value)

  missing_numbers = []

  for i in range(1, len(list_missing_value)):
    if list_missing_value[i] != list_missing_value[i-1] +1:
      missing_numbers.append(list_missing_value[i-1]+1)

  return missing_numbers

In [9]:
list_missing = [1, 4, 3, 2, 5, 8, 7, 10]

In [10]:
missing_value(list_missing)

[6, 9]

In [23]:
list_missing = [1,4,3,2,5,8,7,10] #correct but cannot use in general list, the length is wrong

list_missing.sort ()

missing_num = []

for i in range (1, len(list_missing)):
  if i not in list_missing:
    missing_num.append(i)

print(missing_num)

[6]


In [11]:
#write a function to remove duplicates from a list of numbers
#empty list,create a new list from original list without duplicate

list_duplicate = [100, 20, -30, 100, 20, 0, -30]

#create a new list
new_list = []

#iterate and compare if not in the new list, save it in new list
for i in list_duplicate:
  if i not in new_list:
    new_list.append(i)

print (new_list)

[100, 20, -30, 0]


In [26]:
#code aishah
def remove_duplicates(list_duplicate):
  new_list = []

  for i in list_duplicate:
    if i not in new_list:
      new_list.append(i)

  return (new_list)

In [27]:
list_duplicate = [100, 20, -30, 100, 20, 0, -30, -4, 0, -10, -4]

In [28]:
remove_duplicates(list_duplicate)

[100, 20, -30, 0, -4, -10]

In [25]:
#write a function to remove duplicates from a list of numbers
#empty list,create a new list from original list without duplicate

list_duplicate = [100, 20, -30, 100, 20, 0, -30]

#create a new list
new_list = []

#iterate and compare if not in the new list, save it in new list
for i in list_duplicate:
  if i not in new_list:
    new_list.append(i)
  #then compare with a new list to remove the item in the original list
    if i in new_list:
       list_duplicate.remove(i)

print(list_duplicate)

[100, 20, 0, -30]


In [29]:
#code dr obay
#function is general for any to be use later

def remove_dup(x):

  new_list = [] #100

  for i in x: #100
    if i not in new_list: #True
      new_list.append(i)

  return (new_list)

In [39]:
list_m = [5, 5, 5, 5, 1, 1]

In [40]:
remove_dup(list_m)

[5, 1]

In [32]:
list_a = [22, 88, -20, 88, 2.5, 22, 0]
remove_dup(list_a)

[22, 88, -20, 2.5, 0]

In [33]:
#another solution but not efficient

def remove_dup1(x):

  for i in x:
    if x.count(i) > 1:
      x.remove(i)

  return x

In [36]:
list_dup3 = [100, 20, -30, 100, 20, 0, -30, -4, 0, -4, -30]

In [38]:
remove_dup1(list_dup3)

[100, 20, -4, 0, -4, -30]

### **Third Party Libraries:**

**Pandas** : Python Data Analysis Library, open source (data wrangling, manipulating data)

**Numpy** : Numerical Python

**Scipy** : Scientific Python

**Matplotlib** : Plotting Library for Python (Data Visualization)

**Plotly** : Data Cleaning

In [41]:
import pandas as pd

''' creating a sample of dataset by using dictionary'''
''' creating a dataframe from the dictionary'''
''' keys are the column (features) and the values (cases) are the data'''

mydata = {
    'Name':['Mohammed', 'Nurul', 'Aziz', 'Fatimah'],
    'Age':[23, 32, 30, 27],
    'City':['Kuala Lumpur', 'Kuantan', 'Shah Alam', 'Selangor'],
    'Salary': [5000, 7000, 12000, 9000]
}

mydata

{'Name': ['Mohammed', 'Nurul', 'Aziz', 'Fatimah'],
 'Age': [23, 32, 30, 27],
 'City': ['Kuala Lumpur', 'Kuantan', 'Shah Alam', 'Selangor'],
 'Salary': [5000, 7000, 12000, 9000]}

In [42]:
type(mydata)

dict

In [44]:
#convert dictionary to dataframe

df = pd.DataFrame(mydata)

#call the dataframe from the first column/rows
df.head()

Name  Age          City  Salary
0  Mohammed   23  Kuala Lumpur    5000
1     Nurul   32       Kuantan    7000
2      Aziz   30     Shah Alam   12000
3   Fatimah   27      Selangor    9000

add column or rows means concatinated

In [45]:
data1 = {
    'A':['A1', 'A2', 'A3', 'A4'],
    'B':['B1', 'B2', 'B3', 'B4'],
    'C':['C1', 'C2', 'C3', 'C4'],
    'D':['D1', 'D2', 'D3', 'D4']

}

data2 = {
    'A':['A5', 'A6', 'A7', 'A8'],
    'B':['B5', 'B6', 'B7', 'B8'],
    'C':['C5', 'C6', 'C7', 'C8'],
    'D':['D5', 'D6', 'D7', 'D8']

}

df_data1 = pd.DataFrame(data1)

df_data2 = pd.DataFrame(data2)


In [46]:
df_data1.head()

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [47]:
df_data2.head()

A   B   C   D
0  A5  B5  C5  D5
1  A6  B6  C6  D6
2  A7  B7  C7  D7
3  A8  B8  C8  D8

In [52]:
#concatinated rows #two datasets combined as one
#index of the list

df_data1_data2 = [df_data1, df_data2]

df_1_2 = pd.concat(df_data1_data2)

df_1_2.head(8)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
0  A5  B5  C5  D5
1  A6  B6  C6  D6
2  A7  B7  C7  D7
3  A8  B8  C8  D8

In [53]:
#reset the index/index reseting

df_1_2 = df_1_2.reset_index(drop=True) #drop the old index,true means changing the parameter
#right now drop is False is the Default
#if want to use drop, drop need to be true

df_1_2.head(8)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
4  A5  B5  C5  D5
5  A6  B6  C6  D6
6  A7  B7  C7  D7
7  A8  B8  C8  D8

In [54]:
#concatinate column
#data must be equivalent to each other

data3 = {
    'E':['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
    'F':['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'],

}

df_data3 = pd.DataFrame(data3)

df_data3.head(8)

E   F
0  E1  F1
1  E2  F2
2  E3  F3
3  E4  F4
4  E5  F5
5  E6  F6
6  E7  F7
7  E8  F8

In [57]:
#df_1_2_data3 = [df_1_2, df_data3]

df_all = [df_1_2, df_data3]

df_all = pd.concat(df_all, axis=1) #default axis is zero

df_all.head(8)


A   B   C   D   E   F
0  A1  B1  C1  D1  E1  F1
1  A2  B2  C2  D2  E2  F2
2  A3  B3  C3  D3  E3  F3
3  A4  B4  C4  D4  E4  F4
4  A5  B5  C5  D5  E5  F5
5  A6  B6  C6  D6  E6  F6
6  A7  B7  C7  D7  E7  F7
7  A8  B8  C8  D8  E8  F8

In [58]:
#check how much column and rows do we have
# (rows, columns)
df_all.shape

(8, 6)

In [63]:
#create your own datasets, concatenate in terms of rows once, and in terms of columns once again

#create dummy datasets
dumm_data1 = {
    'ID':[110, 120, 130, 144, 156, 167, 176, 188],
    'Name':['Bella', 'Aishah', 'Maryam', 'Nur', 'Ain', 'Aina', 'Ali', 'Abu'],
    'Age':[25, 28, 30, 27, 22, 24, 26, 31],
    'Status':['Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married']

}

dumm_data2 = {
    'ID':[199, 103, 432, 225, 135, 143, 158, 160],
    'Name':['Nor', 'Nabil', 'Neil', 'Wahida', 'Saras', 'Abid', 'Kookie', 'Ji Hyo'],
    'Age':[18, 34, 35, 20, 29, 28, 23, 38],
    'Status':['Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married']

}

#change dict to dataframe

df_dumm_data1 = pd.DataFrame(dumm_data1)

df_dumm_data2 = pd.DataFrame(dumm_data2)



In [64]:
#concatinated rows

df_dummdata = [df_dumm_data1 , df_dumm_data2 ]

df_dummdata12 = pd.concat(df_dummdata)

df_dummdata12.head(16)

ID    Name  Age   Status
0  110   Bella   25   Single
1  120  Aishah   28  Married
2  130  Maryam   30   Single
3  144     Nur   27  Married
4  156     Ain   22   Single
5  167    Aina   24  Married
6  176     Ali   26   Single
7  188     Abu   31  Married
0  199     Nor   18   Single
1  103   Nabil   34  Married
2  432    Neil   35   Single
3  225  Wahida   20  Married
4  135   Saras   29   Single
5  143    Abid   28  Married
6  158  Kookie   23   Single
7  160  Ji Hyo   38  Married

In [65]:
#reset the index/index reseting

df_dummdata12 = df_dummdata12.reset_index(drop=True)

df_dummdata12.head(16)

ID    Name  Age   Status
0   110   Bella   25   Single
1   120  Aishah   28  Married
2   130  Maryam   30   Single
3   144     Nur   27  Married
4   156     Ain   22   Single
5   167    Aina   24  Married
6   176     Ali   26   Single
7   188     Abu   31  Married
8   199     Nor   18   Single
9   103   Nabil   34  Married
10  432    Neil   35   Single
11  225  Wahida   20  Married
12  135   Saras   29   Single
13  143    Abid   28  Married
14  158  Kookie   23   Single
15  160  Ji Hyo   38  Married

In [66]:
#create datasets to concatinate column

dumm_data3 = {

    'City':['Jengka', 'Temerloh', 'Bachok', 'Kuantan', 'Pekan', 'Kota Bharu', 'Sibu', 'Kuching', 'Jengka', 'Temerloh', 'Bachok', 'Kuantan', 'Pekan', 'Kota Bharu', 'Sibu', 'Kuching'],
    'Total Family Members':[9, 2, 4, 6, 7, 8, 4, 3, 5, 2, 4, 6, 7, 8, 4, 3 ],

}

df_dummdata3 = pd.DataFrame(dumm_data3)

df_dummdata3.head(16)

City  Total Family Members
0       Jengka                     9
1     Temerloh                     2
2       Bachok                     4
3      Kuantan                     6
4        Pekan                     7
5   Kota Bharu                     8
6         Sibu                     4
7      Kuching                     3
8       Jengka                     5
9     Temerloh                     2
10      Bachok                     4
11     Kuantan                     6
12       Pekan                     7
13  Kota Bharu                     8
14        Sibu                     4
15     Kuching                     3

In [105]:
#concatinate column

df_alldummdata = [df_dummdata12, df_dummdata3]

df_alldummdata = pd.concat(df_alldummdata, axis=1) #default axis is zero

df_alldummdata.head(16)

ID    Name  Age   Status        City  Total Family Members
0   110   Bella   25   Single      Jengka                     9
1   120  Aishah   28  Married    Temerloh                     2
2   130  Maryam   30   Single      Bachok                     4
3   144     Nur   27  Married     Kuantan                     6
4   156     Ain   22   Single       Pekan                     7
5   167    Aina   24  Married  Kota Bharu                     8
6   176     Ali   26   Single        Sibu                     4
7   188     Abu   31  Married     Kuching                     3
8   199     Nor   18   Single      Jengka                     5
9   103   Nabil   34  Married    Temerloh                     2
10  432    Neil   35   Single      Bachok                     4
11  225  Wahida   20  Married     Kuantan                     6
12  135   Saras   29   Single       Pekan                     7
13  143    Abid   28  Married  Kota Bharu                     8
14  158  Kookie   23   Single        Sibu                     4
15  160  Ji Hyo   38  Married     Kuching                     3

In [70]:
import pandas as pd

df = pd.read_csv('NFLX.csv')

df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [71]:
#random data in datasets
df.sample()

Date       Open       High    Low      Close  Adj Close    Volume
96  2016-05-05  90.910004  92.080002  89.25  89.370003  89.370003  10368500

In [72]:
#put how many random data wants in the bracket
df.sample(5)

Date        Open        High         Low       Close   Adj Close  \
398  2017-07-18  176.119995  185.000000  174.240005  183.600006  183.600006   
430  2017-08-31  175.449997  176.240005  173.860001  174.710007  174.710007   
7    2015-12-28  117.260002  117.349998  113.849998  117.110001  117.110001   
992  2019-11-25  308.829987  315.730011  305.250000  315.549988  315.549988   
525  2018-01-18  220.339996  220.580002  216.550003  220.330002  220.330002   

       Volume  
398  41587400  
430   6941000  
7     8424300  
992   7873900  
525   8225300

In [73]:
#show until what until what
df.index

RangeIndex(start=0, stop=1007, step=1)

In [74]:
df.shape

(1007, 7)

In [75]:
#shows the name of the columns #columns is a bunch of strings, its considered as object
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [76]:
#statistical information
#mean/average
#normal distribution

df.describe()

Open         High          Low        Close    Adj Close  \
count  1007.000000  1007.000000  1007.000000  1007.000000  1007.000000   
mean    226.708094   229.972979   223.105690   226.670159   226.670159   
std     103.305422   104.851349   101.458611   103.203785   103.203785   
min      80.570000    84.699997    79.949997    82.790001    82.790001   
25%     125.779999   127.165001   124.355000   125.514999   125.514999   
50%     197.850006   199.440002   195.330002   198.000000   198.000000   
75%     325.529999   330.835006   318.869995   325.220001   325.220001   
max     421.380005   423.209991   413.079987   418.970001   418.970001   

             Volume  
count  1.007000e+03  
mean   9.730586e+06  
std    6.398967e+06  
min    1.616300e+06  
25%    5.573200e+06  
50%    7.857600e+06  
75%    1.178630e+07  
max    5.841040e+07

In [77]:
#copy data

df2 = df.copy()

df2.head()

Date        Open        High         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [78]:
#calculate only for one feature

df['High'].mean()

229.97297904468715

In [79]:
df['Low'].std()

101.45861102484218

In [80]:
df['Close'].max()

418.970001

In [81]:
df['Close'].min()

82.790001

In [82]:
#call cells

#df.iloc[[index of row], [index of column]]

df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [83]:
df.iloc[[2], [3]]

Low
2  117.919998

In [84]:
df.iloc[0:5, 2:4]

High         Low
0  123.000000  118.089996
1  126.349998  122.419998
2  122.190002  117.919998
3  119.589996  115.660004
4  117.430000  114.860001

In [86]:
#can just mention the number of the row and name of column

#df.loc[[index of row], [index of column]]

df.loc[[2], ['High']]

High
2  122.190002

In [87]:
#copy of some data using iloc function
df3 = df.iloc[:, 0:3]

df3.head()

Date        Open        High
0  2015-12-16  119.800003  123.000000
1  2015-12-17  123.970001  126.349998
2  2015-12-18  120.849998  122.190002
3  2015-12-21  119.510002  119.589996
4  2015-12-22  117.300003  117.430000

In [88]:
#understanding of whole data
#int and float is considered as numerical data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1007 non-null   object 
 1   Open       1007 non-null   float64
 2   High       1007 non-null   float64
 3   Low        1007 non-null   float64
 4   Close      1007 non-null   float64
 5   Adj Close  1007 non-null   float64
 6   Volume     1007 non-null   int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 55.2+ KB


In [89]:
#each column with its data type

df.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [91]:
#this paramenter use to change name for file
df.rename(columns={'High': 'Test'}, inplace=True)

df.head()

Date        Open        Test         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [ ]:
#action taken at the behind at the copy of the data if tak letak parameter

df.rename(columns={'Low': 'Test'})

df.head()

In [92]:
df_test = df.rename(columns={'Low': 'Test'})

df_test.head()

Date        Open        Test        Test       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

**Numpy**

In [93]:
#create library

import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,])

array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
type(array1)

numpy.ndarray

***What is the difference berween List and Array?***

In Python, both lists and arrays are used to store collections of elements, but they have some differences in terms of functionality and implementation. Here's a breakdown of the key differences between lists and arrays in Python:

*Data Type:*
Lists: Lists in Python are a built-in data type and are part of the standard library. They can hold elements of different data types and are very flexible.
Arrays: Arrays in Python are not a built-in data type but are provided by external libraries like NumPy. Arrays are more rigid in terms of data types and often store homogeneous elements (elements of the same data type) for optimized computation.

*Functionality:*
Lists: Lists provide various methods and operations for adding, removing, and manipulating elements.
Arrays: Arrays, particularly those from libraries like NumPy, provide extensive mathematical operations and optimizations for numerical computations.

*Memory Efficiency:*
Lists: Lists in Python are less memory efficient compared to arrays because they store additional metadata for each element, such as the type of the element and its reference count.

*In summary, the choice between using lists or arrays depends on your specific needs. If you're dealing with general data storage and manipulation, lists are more suitable. If you're working with numerical data and require optimized computations, arrays from libraries like NumPy offer better performance and functionality.*

**array vs list**

list can create without any supporting library

array need numpy to be created
array use for 1 datatype/statistic
array can be more efficient than list

In [95]:
#need to convert to array thaen can deal with the data

#creating 2D array eg: 3x3

array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
#creating 3D array

array3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]
                  )

array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [97]:
#number of the item
array1.shape

(9,)

In [98]:
array2.shape

(3, 3)

In [99]:
array3.shape

(3, 3, 3)

In [100]:
#number of dimension
array1.ndim

1

In [101]:
array2.ndim

2

In [102]:
array3.ndim

3

Data that huge gap

pending, group data and come with a range

In [103]:
#using linspace

#can create range category

#first range 200 until 550
#sec range 550 until 900

np.linspace(200, 900, num=3)

array([200., 550., 900.])

In [104]:
np.linspace(200, 900, num=6)

array([200., 340., 480., 620., 760., 900.])

In [107]:
#call dummy data
df_alldummdata.head(16)

ID    Name  Age   Status        City  Total Family Members
0   110   Bella   25   Single      Jengka                     9
1   120  Aishah   28  Married    Temerloh                     2
2   130  Maryam   30   Single      Bachok                     4
3   144     Nur   27  Married     Kuantan                     6
4   156     Ain   22   Single       Pekan                     7
5   167    Aina   24  Married  Kota Bharu                     8
6   176     Ali   26   Single        Sibu                     4
7   188     Abu   31  Married     Kuching                     3
8   199     Nor   18   Single      Jengka                     5
9   103   Nabil   34  Married    Temerloh                     2
10  432    Neil   35   Single      Bachok                     4
11  225  Wahida   20  Married     Kuantan                     6
12  135   Saras   29   Single       Pekan                     7
13  143    Abid   28  Married  Kota Bharu                     8
14  158  Kookie   23   Single        Sibu                     4
15  160  Ji Hyo   38  Married     Kuching                     3

In [109]:
import numpy as np

array_dum = np.array(df_alldummdata)

array_dum


array([[110, 'Bella', 25, 'Single', 'Jengka', 9],
       [120, 'Aishah', 28, 'Married', 'Temerloh', 2],
       [130, 'Maryam', 30, 'Single', 'Bachok', 4],
       [144, 'Nur', 27, 'Married', 'Kuantan', 6],
       [156, 'Ain', 22, 'Single', 'Pekan', 7],
       [167, 'Aina', 24, 'Married', 'Kota Bharu', 8],
       [176, 'Ali', 26, 'Single', 'Sibu', 4],
       [188, 'Abu', 31, 'Married', 'Kuching', 3],
       [199, 'Nor', 18, 'Single', 'Jengka', 5],
       [103, 'Nabil', 34, 'Married', 'Temerloh', 2],
       [432, 'Neil', 35, 'Single', 'Bachok', 4],
       [225, 'Wahida', 20, 'Married', 'Kuantan', 6],
       [135, 'Saras', 29, 'Single', 'Pekan', 7],
       [143, 'Abid', 28, 'Married', 'Kota Bharu', 8],
       [158, 'Kookie', 23, 'Single', 'Sibu', 4],
       [160, 'Ji Hyo', 38, 'Married', 'Kuching', 3]], dtype=object)

In [110]:
array_dum.shape

(16, 6)

In [111]:
array_dum.ndim

2

In [112]:
np.linspace(18, 38, num=3)

array([18., 28., 38.])

In [114]:
df_alldummdata.head(16)

ID    Name  Age   Status        City  Total Family Members
0   110   Bella   25   Single      Jengka                     9
1   120  Aishah   28  Married    Temerloh                     2
2   130  Maryam   30   Single      Bachok                     4
3   144     Nur   27  Married     Kuantan                     6
4   156     Ain   22   Single       Pekan                     7
5   167    Aina   24  Married  Kota Bharu                     8
6   176     Ali   26   Single        Sibu                     4
7   188     Abu   31  Married     Kuching                     3
8   199     Nor   18   Single      Jengka                     5
9   103   Nabil   34  Married    Temerloh                     2
10  432    Neil   35   Single      Bachok                     4
11  225  Wahida   20  Married     Kuantan                     6
12  135   Saras   29   Single       Pekan                     7
13  143    Abid   28  Married  Kota Bharu                     8
14  158  Kookie   23   Single        Sibu                     4
15  160  Ji Hyo   38  Married     Kuching                     3

In [115]:
df_alldummdata.sample()

ID  Name  Age   Status        City  Total Family Members
13  143  Abid   28  Married  Kota Bharu                     8

In [116]:
df_alldummdata.sample(5)

ID    Name  Age   Status      City  Total Family Members
1  120  Aishah   28  Married  Temerloh                     2
3  144     Nur   27  Married   Kuantan                     6
9  103   Nabil   34  Married  Temerloh                     2
8  199     Nor   18   Single    Jengka                     5
2  130  Maryam   30   Single    Bachok                     4

In [117]:
df_alldummdata.iloc[0:5, 2:4]

Age   Status
0   25   Single
1   28  Married
2   30   Single
3   27  Married
4   22   Single

In [118]:
df_alldummdata['Age'].mean()

27.375

In [119]:
df_alldummdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   ID                    16 non-null     int64 
 1   Name                  16 non-null     object
 2   Age                   16 non-null     int64 
 3   Status                16 non-null     object
 4   City                  16 non-null     object
 5   Total Family Members  16 non-null     int64 
dtypes: int64(3), object(3)
memory usage: 896.0+ bytes


In [120]:
df_alldummdata.dtypes

ID                       int64
Name                    object
Age                      int64
Status                  object
City                    object
Total Family Members     int64
dtype: object

In [122]:
df_alldummdata.rename(columns={'Age': 'Test'}, inplace=True)

df_alldummdata.head(16)

ID    Name  Test   Status        City  Total Family Members
0   110   Bella    25   Single      Jengka                     9
1   120  Aishah    28  Married    Temerloh                     2
2   130  Maryam    30   Single      Bachok                     4
3   144     Nur    27  Married     Kuantan                     6
4   156     Ain    22   Single       Pekan                     7
5   167    Aina    24  Married  Kota Bharu                     8
6   176     Ali    26   Single        Sibu                     4
7   188     Abu    31  Married     Kuching                     3
8   199     Nor    18   Single      Jengka                     5
9   103   Nabil    34  Married    Temerloh                     2
10  432    Neil    35   Single      Bachok                     4
11  225  Wahida    20  Married     Kuantan                     6
12  135   Saras    29   Single       Pekan                     7
13  143    Abid    28  Married  Kota Bharu                     8
14  158  Kookie    23   Single        Sibu                     4
15  160  Ji Hyo    38  Married     Kuching                     3